spring:
  application:
    name: url-shortener

aws:
  access-key: ${URL_SHORTENER_AWS_ACCESS_KEY}
  secret-key: ${URL_SHORTENER_AWS_SECRET_KEY}
  dynamo:
    table-name: ${DYNAMO_TABLE_NAME}
    region: ${AWS_REGION}
